[build]
publish = "."
command = ""

[functions]
directory = "netlify/edge-functions"

# Удаляем редирект на Edge Function из netlify.toml
# Edge Function будет вызываться автоматически Netlify для каждого запроса к сайту,
# если она находится в папке edge-functions и не имеет Route.
