[build]
publish = "."
command = ""

[functions]
directory = "netlify/edge-functions"

[[redirects]]
from = "/*"
to = "/.netlify/edge-functions/check-referer-v2" # <- Это имя файла вашей Edge Function
status = 200
force = true
edge = true
