[build]
publish = "."
command = ""

[functions]
directory = "netlify/edge-functions"

# Изменяем редирект для более явного соответствия
[[redirects]]
from = "/*"
to = "/.netlify/edge-functions/check-referer" # Использование edge-functions вместо functions
status = 200
force = true
